apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
    app: demo
spec:
  selector:
    name: web 
  type: LoadBalancer
  ports:
   - port: 8082
     targetPort: 5000
     protocol: TCP